version: '3.8'

services:
  sentiment-app:
    build: .
    ports:
      - "5000:5050"  
    volumes:
      - ./modelki:/app/modelki  
      - ./logs:/app/logs
      - ./templates:/app/templates  
      - ./static:/app/static        
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped